version: '3'
services:
  web:
    image: dane-visual-feature-extraction-worker:latest
    volumes:
      - ./data:/data
      - ./model:/model
      - ./config:/root/.DANE
    container_name: visxp_worker_2
    command: --run-test-file  # NOTE: comment this line to spin up th worker
    logging:
      options:
        max-size: 20m
    restart: unless-stopped