# Important for understanding DANE configs: https://github.com/CLARIAH/DANE/blob/main/DANE/config.py

# Important note:
# FIRST the home dir config is applied (~/.DANE/config.yml),
# THEN the base_config.yml will overwrite anything,
# THEN the local config.yml

#Note: For local testing, copy this file to config.yml (in main dir of this repo)
RABBITMQ:
    HOST: dane-rabbitmq-api.default.svc.cluster.local
    PORT: 5672
    EXCHANGE: DANE-exchange
    RESPONSE_QUEUE: DANE-response-queue
    USER: guest # change this for production mode
    PASSWORD: guest # change this for production mode
ELASTICSEARCH:
    HOST:
        - elasticsearch
    PORT: 9200
    USER: '' # change this for production mode
    PASSWORD: '' # change this for production mode
    SCHEME: http
    INDEX: dane-index-k8s-asr
FILE_SYSTEM:
    BASE_MOUNT: /data # data when running locally
    INPUT_DIR: input-files
    OUTPUT_DIR: output-files
PATHS:
    TEMP_FOLDER: /data/input-files
    OUT_FOLDER: /data/output-files
VISXP_EXTRACT:
    MODEL_BASE_MOUNT: /model
    MODEL_CHECKPOINT_FILE: checkpoint.tar  # should be in MODEL_BASE_MOUNT
    MODEL_CONFIG_FILE: model_config.yml  # should be in MODEL_BASE_MOUNT
    TEST_INPUT_PATH: /data/input-files/testob/visxp_prep__testob.tar.gz
INPUT:
    S3_ENDPOINT_URL: https://s3-host
    MODEL_CHECKPOINT_S3_URI: s3://beng-daan-visxp/model/checkpoint.tar
    MODEL_CONFIG_S3_URI: s3://beng-daan-visxp/model/model_config.yml
    DELETE_ON_COMPLETION: False
OUTPUT:
    DELETE_ON_COMPLETION: True
    TRANSFER_ON_COMPLETION: True
    S3_ENDPOINT_URL: https://s3-host
    S3_BUCKET: beng-daan-visxp  # bucket reserved for 1 type of output
    S3_FOLDER_IN_BUCKET: assets  # folder within the bucket
DANE_DEPENDENCIES:
    - DOWNLOAD