name: Build image and push to ECR

on:
  workflow_call:

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get lowercase repo name
      id: repo-name
      run: echo "REPO_NAME=$(echo ${{github.repository}} | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    - name: Get short SHA
      id: sha
      run: echo "SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Build, tag, and push image to private Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/${{ steps.repo-name.outputs.REPO_NAME }}:${{ steps.sha.outputs.SHA7 }} -t $ECR_REGISTRY/${{ steps.repo-name.outputs.REPO_NAME }}:latest .
        docker push $ECR_REGISTRY/${{ steps.repo-name.outputs.REPO_NAME }} --all-tags
