name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Repository"
      uses: "actions/checkout@v3"

    - name: "Install Python"
      uses: "actions/setup-python@v4"
      with:
        python-version: "3.10"

    - name: "Install poetry"
      run: "pip install --user poetry"

    - name: "Install dev environment"
      run: poetry install --no-interaction --no-ansi

    - name: install libgl1
      run: sudo apt-get install -y libgl1

    - name: install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg --fix-missing

    - name: "pytest"
      run: |
        cp config/config.yml config.yml
        poetry run pytest

    - name: "flake8"
      run: "poetry run flake8"

    - name: "black"
      run: "poetry run black --check ."

    - name: "mypy"
      run: "poetry run mypy ."