name: main branch - test; deploy (ecr, tst, acc, aws)

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - README.md
      - LICENSE
      - docker-compose.yml

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  build-and-push-ecr:
    uses: ./.github/workflows/_build-and-push-ecr.yml
    secrets: inherit
    needs: [test]
